In [152]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline 
import seaborn as sns
import plotly.express as px

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-failure-clinical-data/heart_failure_clinical_records_dataset.csv


In [153]:
filepath = '/kaggle/input/heart-failure-clinical-data/heart_failure_clinical_records_dataset.csv'
heart_data = pd.read_csv(filepath)
heart_data.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [154]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.5 KB


In [155]:
heart_data.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

In [156]:
heart_data.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [157]:
corr_matrix = heart_data.corr()
corr_matrix["DEATH_EVENT"].sort_values(ascending=False)

DEATH_EVENT                 1.000000
serum_creatinine            0.294278
age                         0.253729
high_blood_pressure         0.079351
anaemia                     0.066270
creatinine_phosphokinase    0.062728
diabetes                   -0.001943
sex                        -0.004316
smoking                    -0.012623
platelets                  -0.049139
serum_sodium               -0.195204
ejection_fraction          -0.268603
time                       -0.526964
Name: DEATH_EVENT, dtype: float64

In [158]:
heart_data.drop("time",axis=1)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  DEATH_EVENT  
0          0            1  
1          0            1  
2          1            1  
3          0            1  
4          0            1  
..       ...          ...  
294        1            0  
295        0            0  
296        0            0  
297        1            0  
298        1            0  

[299 rows x 12 columns]

In [245]:
fig = px.histogram(heart_data, x="age",title='Histogram of Age and Death Event', color="DEATH_EVENT",nbins=28, marginal="rug",hover_data=heart_data.columns)
fig.show()

In [ ]:
fig = px.box(heart_data, x="DEATH_EVENT", y="age",title='Boxplot of Death Event and Age', points="all")
fig.show()

In [ ]:
fig = px.box(heart_data, x="DEATH_EVENT", y="age",title='Boxplot of Death Event and Age', points="all")
fig.show()

In [ ]:
fig = px.histogram(heart_data, x="creatinine_phosphokinase",title='Histogram of Creatinine_phosphokinase and Death Event', color="DEATH_EVENT",nbins=28, marginal="rug",hover_data=heart_data.columns)
fig.show()

In [ ]:
dia = heart_data['diabetes'].value_counts().reset_index()
dia.columns = ['diabetes','count']
fig = px.pie( dia,values='count', names="diabetes", title='Diabetes Pie chart')
fig.show()

In [ ]:
fig = px.histogram(heart_data, x="ejection_fraction",title='Histogram of Ejection Fraction and Death Event', color="DEATH_EVENT",nbins=28, marginal="rug",hover_data=heart_data.columns)
fig.show()

In [ ]:
fig = px.box(heart_data, x="DEATH_EVENT", y="ejection_fraction",title='Boxplot of Death Event and Ejection Fraction', points="all")
fig.show()

In [ ]:
hbp = heart_data['high_blood_pressure'].value_counts().reset_index()
hbp.columns = ['high_blood_pressure','count']
fig = px.pie( hbp,values='count', names="high_blood_pressure", title='High Blood Pressure Pie chart')
fig.show()

In [ ]:
fig = px.histogram(heart_data, x="platelets",title='Histogram of Platelets and Death Event', color="DEATH_EVENT",nbins=28, marginal="rug",hover_data=heart_data.columns)
fig.show()

In [ ]:
fig = px.box(heart_data, x="DEATH_EVENT", y="platelets",title='Boxplot of Death Event and Platelets', points="all")
fig.show()

In [ ]:
fig = px.histogram(heart_data, x="serum_creatinine",title='Histogram of Serum Creatinine and Death Event', color="DEATH_EVENT",nbins=28, marginal="rug",hover_data=heart_data.columns)
fig.show()

In [ ]:
fig = px.box(heart_data, x="DEATH_EVENT", y="serum_creatinine",title='Boxplot of Death Event and Serum Creatinine', points="all")
fig.show()

In [ ]:
fig = px.histogram(heart_data, x="serum_sodium",title='Histogram of Serum Sodium and Death Event', color="DEATH_EVENT",nbins=28, marginal="rug",hover_data=heart_data.columns)
fig.show()

In [ ]:
fig = px.box(heart_data, x="DEATH_EVENT", y="serum_sodium",title='Boxplot of Death Event and Serum Sodium', points="all")
fig.show()

In [ ]:
sm = heart_data['smoking'].value_counts().reset_index()
sm.columns = ['smoking','count']
fig = px.pie( sm,values='count', names="smoking", title="Smoker's Pie chart")
fig.show()

In [ ]:
plt.figure(figsize=(15,10))
plt.title("Correlation Matrix")
sns.heatmap(heart_data.corr(), annot=True)

In [159]:
Features=["serum_creatinine","ejection_fraction"]
X = heart_data[Features]
y = heart_data["DEATH_EVENT"]

In [160]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 2)

In [161]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

log_clf = LogisticRegression(random_state=1).fit(X_train, y_train)
log_pred = log_clf.predict(X_test)
accuracy_score(y_test, log_pred)

0.8166666666666667

In [162]:
f1_score(y_test, log_pred, average='weighted')

0.7998008761449622

In [163]:
from sklearn.metrics import confusion_matrix

conf_mat = confusion_matrix(y_test, log_pred)
print(conf_mat)

[[41  2]
 [ 9  8]]


In [164]:
from sklearn import svm

svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)
svm_pred = log_clf.predict(X_test)
accuracy_score(y_test, svm_pred)

0.8166666666666667

In [165]:
f1_score(y_test, svm_pred, average='weighted')

0.7998008761449622

In [166]:
conf_mat = confusion_matrix(y_test, svm_pred)
print(conf_mat)

[[41  2]
 [ 9  8]]


In [167]:
from sklearn.neighbors import KNeighborsClassifier
KN_clf = KNeighborsClassifier(n_neighbors=3)
KN_clf.fit(X_train, y_train)
KN_pred = log_clf.predict(X_test)
accuracy_score(y_test, KN_pred)

0.8166666666666667

In [168]:
f1_score(y_test, KN_pred, average='weighted')

0.7998008761449622

In [169]:
conf_mat = confusion_matrix(y_test, KN_pred)
print(conf_mat)

[[41  2]
 [ 9  8]]


In [170]:
from xgboost import XGBClassifier

xgb_clf = XGBClassifier(n_estimators=1000,booster = 'gblinear', learning_rate=0.3 )
xgb_clf.fit(X_train, y_train,early_stopping_rounds=4, 
             eval_set=[(X_test, y_test)], 
             verbose=False)
xgb_pred = xgb_clf.predict(X_test)
accuracy_score(y_test, xgb_pred)

[14:30:05] WARNING: ../src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


0.8166666666666667

In [171]:
f1_score(y_test, xgb_pred, average='weighted')

0.7998008761449622

In [172]:
conf_mat = confusion_matrix(y_test, xgb_pred)
print(conf_mat)

[[41  2]
 [ 9  8]]


In [173]:
import lightgbm as lgb

lgb_clf = lgb.LGBMClassifier(boosting_type='gbdt',num_leaves=31, max_depth= 2 ,learning_rate =0.001, n_estimators=900 )
lgb_clf.fit(X_train, y_train)
lgb_pred=lgb_clf.predict(X_test)
accuracy_score(y_test, lgb_pred)

0.8

In [174]:
f1_score(y_test, lgb_pred, average='weighted')

0.791111111111111

In [175]:
conf_mat = confusion_matrix(y_test, lgb_pred)
print(conf_mat)

[[39  4]
 [ 8  9]]


In [231]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
X_train, y_train = make_classification(n_samples=1000, n_features=3,
                           n_informative=2, n_redundant=0,
                           random_state=40, shuffle=True)
rfc_clf = RandomForestClassifier(max_depth=7,min_samples_leaf= 1, random_state=42)
rfc_clf.fit(X, y)
rfc_pred=rfc_clf.predict(X_test)
accuracy_score(y_test, rfc_pred)

0.8666666666666667

In [232]:
f1_score(y_test, rfc_pred, average='weighted')

0.8666666666666667

In [233]:
conf_mat = confusion_matrix(y_test, rfc_pred)
print(conf_mat)

[[39  4]
 [ 4 13]]


In [234]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(X, y)
dt_pred=dt_clf.predict(X_test)
accuracy_score(y_test, dt_pred)

0.8833333333333333

In [235]:
f1_score(y_test, dt_pred, average='weighted')

0.8822361546499476

In [236]:
conf_mat = confusion_matrix(y_test, dt_pred)
print(conf_mat)

[[40  3]
 [ 4 13]]
